/* global window */
/* ----------------------------------------------------------
   ClinicaPC Kiosk — Placeholder PC data
   In production this gets replaced by your detected-equipment
   payload. Fields marked `present:false` are hidden in the UI.
   ---------------------------------------------------------- */

window.KIOSK_DATA = {
  unit: {
    id: "EQ-0247",
    name: "ASUS ROG STRIX G16",
    family: "Gaming Laptop · 16\"",
    sku: "G614JV-N3170W",
    state: "Reacondicionado Grado A+",
    price: { amount: 1299, currency: "€", strike: 1599 },
    warranty: "24 meses garantía ClinicaPC",
  },
  specs: [
    {
      id: "cpu",
      present: true,
      label: "Procesador",
      family: "CPU",
      value: "Intel Core i7",
      detail: "13650HX · 14 núcleos · hasta 4.9 GHz",
      benchScore: 86,
      benchLabel: "vs. PC de gama media",
      summary: "El cerebro del equipo. Más núcleos y más velocidad significan que abre programas al instante y no se atasca con varias cosas a la vez.",
      pros: ["Edición de vídeo sin tirones", "Multitarea pesada", "Compilar / renderizar rápido"],
      angle: 8,
    },
    {
      id: "gpu",
      present: true,
      label: "Gráfica",
      family: "GPU",
      value: "NVIDIA RTX 4060",
      detail: "8 GB GDDR6 · Ray Tracing · DLSS 3.5",
      benchScore: 92,
      benchLabel: "rendimiento gaming 1080p",
      summary: "La pieza que dibuja en pantalla. Esta gráfica está pensada para jugar a calidad alta y para acelerar IA, edición y modelado 3D.",
      pros: ["Juegos AAA en alto", "Streaming sin lag", "Aceleración IA local"],
      angle: 50,
    },
    {
      id: "ram",
      present: true,
      label: "Memoria",
      family: "RAM",
      value: "32 GB DDR5",
      detail: "4800 MHz · 2× SO-DIMM · ampliable a 64 GB",
      benchScore: 90,
      benchLabel: "vs. portátil estándar (8 GB)",
      summary: "El espacio de trabajo del PC. Cuanta más RAM, más pestañas, programas y proyectos abiertos a la vez sin que vaya lento.",
      pros: ["Decenas de pestañas abiertas", "Photoshop + navegador + Discord", "Máquinas virtuales"],
      angle: 92,
    },
    {
      id: "storage",
      present: true,
      label: "Almacenamiento",
      family: "SSD",
      value: "1 TB NVMe",
      detail: "PCIe 4.0 · 7000 MB/s lectura · M.2 2280",
      benchScore: 95,
      benchLabel: "vs. disco duro tradicional",
      summary: "Donde se guarda todo. Un SSD NVMe es hasta 30× más rápido que un disco duro: el PC arranca en segundos y los juegos cargan al vuelo.",
      pros: ["Arranque en <10 s", "Carga de juegos instantánea", "Transferencia de archivos rápida"],
      angle: 134,
    },
    {
      id: "screen",
      present: true,
      label: "Pantalla",
      family: "DISPLAY",
      value: "16″ QHD 240 Hz",
      detail: "2560 × 1600 · IPS · 100% DCI-P3 · G-Sync",
      benchScore: 88,
      benchLabel: "fluidez en juegos competitivos",
      summary: "240 imágenes por segundo en alta resolución. Todo se ve nítido y el movimiento es mucho más suave que en una pantalla normal.",
      pros: ["Juegos competitivos", "Edición de foto/vídeo en color real", "Series y películas QHD"],
      angle: 176,
    },
    {
      id: "battery",
      present: true,
      label: "Batería",
      family: "POWER",
      value: "90 Wh",
      detail: "Hasta 8 h uso ofimática · carga rápida 65 %/30 min",
      benchScore: 70,
      benchLabel: "autonomía vs. gaming laptops",
      summary: "Una jornada de trabajo lejos del enchufe en uso normal. Para jugar se recomienda con el cargador conectado.",
      pros: ["Universidad / oficina", "Carga rápida USB-C", "Sin enchufe para tareas ligeras"],
      angle: 218,
    },
    {
      id: "wifi",
      present: true,
      label: "Conectividad",
      family: "WIFI 6E",
      value: "WiFi 6E + BT 5.3",
      detail: "Tri-banda 6 GHz · Bluetooth 5.3 · 2.5 GbE",
      benchScore: 84,
      benchLabel: "vs. WiFi 5",
      summary: "La última generación de WiFi: hasta 3× más rápido y con menos interferencias. Bluetooth 5.3 para mando, auriculares y periféricos.",
      pros: ["Streaming 4K sin cortes", "Partidas con ping bajo", "Latencia mínima en BT"],
      angle: 260,
    },
    {
      id: "camera",
      present: true,
      label: "Cámara",
      family: "WEBCAM",
      value: "1080p FHD",
      detail: "Con obturador de privacidad · micrófono dual",
      benchScore: 65,
      benchLabel: "calidad llamadas",
      summary: "Resolución Full HD para videollamadas con buena cara. Lleva tapa física, así que cuando no la usas estás 100% privado.",
      pros: ["Teams / Zoom / Meet", "Privacidad por hardware", "Reconocimiento facial"],
      angle: 302,
    },
    {
      id: "ports",
      present: true,
      label: "Puertos",
      family: "I/O",
      value: "USB-C × 2 · HDMI 2.1",
      detail: "Thunderbolt 4 · USB-A × 3 · RJ-45 · jack 3.5",
      summary: "Todo lo que necesitas conectar sin adaptadores: dos monitores externos por HDMI/USB-C, red por cable, periféricos USB-A clásicos.",
      pros: ["Dos monitores externos", "Carga por USB-C", "LAN gigabit"],
      angle: 344,
      compact: true,
    },
    {
      id: "os",
      present: true,
      label: "Sistema",
      family: "OS",
      value: "Windows 11 Home",
      detail: "Licencia original · activada · 64-bit",
      summary: "Sistema operativo más reciente, con todas las actualizaciones de seguridad al día y licencia legal incluida.",
      pros: ["Activado de fábrica", "Office compatible", "Soporte oficial Microsoft"],
      angle: 26,
      compact: true,
    },
  ],

  attract: [
    {
      eyebrow: "ClinicaPC · Análisis en vivo",
      title: "Este equipo",
      titleAccent: "te está observando.",
      sub: "Conéctate · escanea · descubre cada componente en 30 segundos.",
    },
    {
      eyebrow: "Sin tecnicismos",
      title: "Lo entiendes",
      titleAccent: "aunque no seas técnico.",
      sub: "Te traducimos cada spec a lenguaje de calle.",
    },
    {
      eyebrow: "Reacondicionados con cabeza",
      title: "Hasta 60% menos",
      titleAccent: "que comprarlo nuevo.",
      sub: "Probado, limpiado y con 24 meses de garantía.",
    },
  ],
};
